--OtherStuff
--Scoreboard
resource.AddFile( "materials/PirateShipWars/old_parchment.vmt" )
resource.AddFile( "materials/PirateShipWars/old_parchment.vtf" )
resource.AddFile( "materials/PirateShipWars/PSWlogo.vmt" )
resource.AddFile( "materials/PirateShipWars/PSWlogo.vtf" )

--smoke effects
resource.AddFile( "materials/effects/muzzle01.vmt" )
resource.AddFile( "materials/effects/muzzle01.vtf" )
resource.AddFile( "materials/effects/smoke01.vmt" )
resource.AddFile( "materials/effects/smoke01.vtf" )
resource.AddFile( "materials/effects/smoke02.vmt" )
resource.AddFile( "materials/effects/smoke02.vtf" )

--Frigate01 Models
--cannon + base
resource.AddFile( "models/frigate01/cannon/cannon.dx80.vtx" )
resource.AddFile( "models/frigate01/cannon/cannon.dx90.vtx" )
resource.AddFile( "models/frigate01/cannon/cannon.mdl" )
resource.AddFile( "models/frigate01/cannon/cannon.phy" )
resource.AddFile( "models/frigate01/cannon/cannon.sw.vtx" )
resource.AddFile( "models/frigate01/cannon/cannon.vvd" )
resource.AddFile( "models/frigate01/cannon/cannonbase.dx80.vtx" )
resource.AddFile( "models/frigate01/cannon/cannonbase.dx90.vtx" )
resource.AddFile( "models/frigate01/cannon/cannonbase.mdl" )
resource.AddFile( "models/frigate01/cannon/cannonbase.phy" )
resource.AddFile( "models/frigate01/cannon/cannonbase.sw.vtx" )
resource.AddFile( "models/frigate01/cannon/cannonbase.vvd" )

--Helm
resource.AddFile( "models/frigate01/helm/helm.dx80.vtx" )
resource.AddFile( "models/frigate01/helm/helm.dx90.vtx" )
resource.AddFile( "models/frigate01/helm/helm.mdl" )
resource.AddFile( "models/frigate01/helm/helm.phy" )
resource.AddFile( "models/frigate01/helm/helm.sw.vtx" )
resource.AddFile( "models/frigate01/helm/helm.vvd" )

--masts
resource.AddFile( "models/frigate01/masts/BackMast.dx80.vtx" )
resource.AddFile( "models/frigate01/masts/BackMast.dx90.vtx" )
resource.AddFile( "models/frigate01/masts/BackMast.mdl" )
resource.AddFile( "models/frigate01/masts/BackMast.phy" )
resource.AddFile( "models/frigate01/masts/BackMast.sw.vtx" )
resource.AddFile( "models/frigate01/masts/BackMast.vvd" )
resource.AddFile( "models/frigate01/masts/FrontMast.dx80.vtx" )
resource.AddFile( "models/frigate01/masts/FrontMast.dx90.vtx" )
resource.AddFile( "models/frigate01/masts/FrontMast.mdl" )
resource.AddFile( "models/frigate01/masts/FrontMast.phy" )
resource.AddFile( "models/frigate01/masts/FrontMast.sw.vtx" )
resource.AddFile( "models/frigate01/masts/FrontMast.vvd" )
resource.AddFile( "models/frigate01/masts/MiddleMast.dx80.vtx" )
resource.AddFile( "models/frigate01/masts/MiddleMast.dx90.vtx" )
resource.AddFile( "models/frigate01/masts/MiddleMast.mdl" )
resource.AddFile( "models/frigate01/masts/MiddleMast.phy" )
resource.AddFile( "models/frigate01/masts/MiddleMast.sw.vtx" )
resource.AddFile( "models/frigate01/masts/MiddleMast.vvd" )

--sails
resource.AddFile( "models/frigate01/sails/BackSails.dx80.vtx" )
resource.AddFile( "models/frigate01/sails/BackSails.dx90.vtx" )
resource.AddFile( "models/frigate01/sails/BackSails.mdl" )
resource.AddFile( "models/frigate01/sails/BackSails.phy" )
resource.AddFile( "models/frigate01/sails/BackSails.sw.vtx" )
resource.AddFile( "models/frigate01/sails/BackSails.vvd" )
resource.AddFile( "models/frigate01/sails/FrontSails.dx80.vtx" )
resource.AddFile( "models/frigate01/sails/FrontSails.dx90.vtx" )
resource.AddFile( "models/frigate01/sails/FrontSails.mdl" )
resource.AddFile( "models/frigate01/sails/FrontSails.phy" )
resource.AddFile( "models/frigate01/sails/FrontSails.sw.vtx" )
resource.AddFile( "models/frigate01/sails/FrontSails.vvd" )
resource.AddFile( "models/frigate01/sails/MiddleSails.dx80.vtx" )
resource.AddFile( "models/frigate01/sails/MiddleSails.dx90.vtx" )
resource.AddFile( "models/frigate01/sails/MiddleSails.mdl" )
resource.AddFile( "models/frigate01/sails/MiddleSails.phy" )
resource.AddFile( "models/frigate01/sails/MiddleSails.sw.vtx" )
resource.AddFile( "models/frigate01/sails/MiddleSails.vvd" )

--shipsother
resource.AddFile( "models/frigate01/shipsother/Lantern01.dx80.vtx" )
resource.AddFile( "models/frigate01/shipsother/Lantern01.dx90.vtx" )
resource.AddFile( "models/frigate01/shipsother/Lantern01.mdl" )
resource.AddFile( "models/frigate01/shipsother/Lantern01.phy" )
resource.AddFile( "models/frigate01/shipsother/Lantern01.sw.vtx" )
resource.AddFile( "models/frigate01/shipsother/Lantern01.vvd" )
resource.AddFile( "models/frigate01/shipsother/Lantern02.dx80.vtx" )
resource.AddFile( "models/frigate01/shipsother/Lantern02.dx90.vtx" )
resource.AddFile( "models/frigate01/shipsother/Lantern02.mdl" )
resource.AddFile( "models/frigate01/shipsother/Lantern02.phy" )
resource.AddFile( "models/frigate01/shipsother/Lantern02.sw.vtx" )
resource.AddFile( "models/frigate01/shipsother/Lantern02.vvd" )

--Frigate01 Textures
--Modeltextures
resource.AddFile( "materials/textures/modeltextures/cannon.vmt" )
resource.AddFile( "materials/textures/modeltextures/gold.vmt" )
resource.AddFile( "materials/textures/modeltextures/metal_black.vmt" )
resource.AddFile( "materials/textures/modeltextures/rope.vmt" )
resource.AddFile( "materials/textures/modeltextures/sail.vmt" )
resource.AddFile( "materials/textures/modeltextures/shipglass_01.vmt" )
resource.AddFile( "materials/textures/modeltextures/shipglass_02.vmt" )
resource.AddFile( "materials/textures/modeltextures/shiprope_01.vmt" )
resource.AddFile( "materials/textures/modeltextures/shiprope_02.vmt" )
resource.AddFile( "materials/textures/modeltextures/shipwood_01.vmt" )
resource.AddFile( "materials/textures/modeltextures/shipwood_02.vmt" )
resource.AddFile( "materials/textures/modeltextures/wax.vmt" )

--Textures
resource.AddFile( "materials/textures/ship/sail/sail.vmt" )
resource.AddFile( "materials/textures/ship/sail/sail.vtf" )
resource.AddFile( "materials/textures/ship/sail/sail_normal.vtf" )

resource.AddFile( "materials/textures/ship/wood/shipwood_01.vmt" )
resource.AddFile( "materials/textures/ship/wood/shipwood_01.vtf" )
resource.AddFile( "materials/textures/ship/wood/shipwood_02.vmt" )
resource.AddFile( "materials/textures/ship/wood/shipwood_02.vtf" )

resource.AddFile( "materials/textures/ship/ballbearing.vmt" )
resource.AddFile( "materials/textures/ship/cannon.vmt" )
resource.AddFile( "materials/textures/ship/cannon.vtf" )
resource.AddFile( "materials/textures/ship/cannon_nrm.vtf" )
resource.AddFile( "materials/textures/ship/cannonball.vmt" )
resource.AddFile( "materials/textures/ship/cannonball.vtf" )
resource.AddFile( "materials/textures/ship/gold.vmt" )
resource.AddFile( "materials/textures/ship/gold.vtf" )
resource.AddFile( "materials/textures/ship/gold_nrm.vtf" )
resource.AddFile( "materials/textures/ship/metal_black.vmt" )
resource.AddFile( "materials/textures/ship/metal_black.vtf" )
resource.AddFile( "materials/textures/ship/metal_black_nrm.vtf" )
resource.AddFile( "materials/textures/ship/shipglass_02.vmt" )
resource.AddFile( "materials/textures/ship/shipglass_02.vmt" )
resource.AddFile( "materials/textures/ship/shipglass_02_ref.vmt" )
resource.AddFile( "materials/textures/ship/shiprope_01.vmt" )
resource.AddFile( "materials/textures/ship/shiprope_01.vtf" )
resource.AddFile( "materials/textures/ship/shiprope_02.vmt" )
resource.AddFile( "materials/textures/ship/shiprope_02.vtf" )
resource.AddFile( "materials/textures/ship/wax.vmt" )
resource.AddFile( "materials/textures/ship/wax.vtf" )

--Skirmisher Player Model
--Textures
resource.AddFile( "materials/models/player/skirmisher/eyeball_l.vmt" )
resource.AddFile( "materials/models/player/skirmisher/eyeball_l.vtf" )
resource.AddFile( "materials/models/player/skirmisher/eyeball_r.vmt" )
resource.AddFile( "materials/models/player/skirmisher/eyeball_r.vtf" )
resource.AddFile( "materials/models/player/skirmisher/eyes.vmt" )
resource.AddFile( "materials/models/player/skirmisher/eyes.vtf" )
resource.AddFile( "materials/models/player/skirmisher/glint.vmt" )
resource.AddFile( "materials/models/player/skirmisher/glint.vtf" )
resource.AddFile( "materials/models/player/skirmisher/pupil_l.vmt" )
resource.AddFile( "materials/models/player/skirmisher/pupil_l.vtf" )
resource.AddFile( "materials/models/player/skirmisher/pupil_r.vmt" )
resource.AddFile( "materials/models/player/skirmisher/pupil_r.vtf" )
resource.AddFile( "materials/models/player/skirmisher/skirmisher.vmt" )
resource.AddFile( "materials/models/player/skirmisher/skirmisher.vtf" )
resource.AddFile( "materials/models/player/skirmisher/skirmisher_diffuseshading.vtf" )
resource.AddFile( "materials/models/player/skirmisher/skirmisher_lightwarp.vtf" )
resource.AddFile( "materials/models/player/skirmisher/skirmisher_normal.vtf" )
resource.AddFile( "materials/models/player/skirmisher/skirmisher_rtnl.vtf" )
resource.AddFile( "materials/models/player/skirmisher/skirmteeth.vmt" )
resource.AddFile( "materials/models/player/skirmisher/skirmteeth.vtf" )

--Model
resource.AddFile( "models/player/skirmisher/skirmisher.dx80.vtx" )
resource.AddFile( "models/player/skirmisher/skirmisher.dx90.vtx" )
resource.AddFile( "models/player/skirmisher/skirmisher.mdl" )
resource.AddFile( "models/player/skirmisher/skirmisher.phy" )
resource.AddFile( "models/player/skirmisher/skirmisher.sw.vtx" )
resource.AddFile( "models/player/skirmisher/skirmisher.vvd" )

--Weapons
--SSPistol
resource.AddFile( "materials/models/weapons/w_fancy_flintlock_diffuse.vmt" )
resource.AddFile( "materials/models/weapons/w_fancy_flintlock_diffuse.vtf" )
resource.AddFile( "materials/models/weapons/w_fancy_flintlock_normal.vtf" )
resource.AddFile( "materials/models/weapons/w_fancy_flintlock_RTNL.vtf" )
resource.AddFile( "materials/models/weapons/fancy_flintlock_diffuse.vmt" )
resource.AddFile( "materials/models/weapons/fancy_flintlock_diffuse.vtf" )
resource.AddFile( "materials/models/weapons/fancy_flintlock_normal.vtf" )
resource.AddFile( "materials/models/weapons/fancy_flintlock_RTNL.vtf" )
resource.AddFile( "materials/models/weapons/ss_hands.vmt" )
resource.AddFile( "materials/models/weapons/ss_hands.vtf" )
resource.AddFile( "materials/models/weapons/ss_sleeve.vmt" )
resource.AddFile( "materials/models/weapons/ss_sleeve.vtf" )
resource.AddFile( "materials/models/weapons/ss_sleeve_diffuse.vtf" )
resource.AddFile( "materials/models/weapons/ss_sleeve_normal.vtf" )

resource.AddFile( "models/weapons/w_sspistol/w_sspistol.dx80.vtx" )
resource.AddFile( "models/weapons/w_sspistol/w_sspistol.dx90.vtx" )
resource.AddFile( "models/weapons/w_sspistol/w_sspistol.mdl" )
resource.AddFile( "models/weapons/w_sspistol/w_sspistol.phy" )
resource.AddFile( "models/weapons/w_sspistol/w_sspistol.sw.vtx" )
resource.AddFile( "models/weapons/w_sspistol/w_sspistol.vvd" )
resource.AddFile( "models/weapons/sspistol.dx80.vtx" )
resource.AddFile( "models/weapons/sspistol.dx90.vtx" )
resource.AddFile( "models/weapons/sspistol.mdl" )
resource.AddFile( "models/weapons/sspistol.sw.vtx" )
resource.AddFile( "models/weapons/sspistol.vvd" )
resource.AddFile( "models/weapons/sspistol.xbox.vtx" )

--Musket
resource.AddFile( "materials/models/weapons/w_musket.vmt" )
resource.AddFile( "materials/models/weapons/w_musket.vtf" )
resource.AddFile( "materials/models/weapons/w_musket_normal.vtf" )
resource.AddFile( "materials/models/weapons/v_musket.vmt" )
resource.AddFile( "materials/models/weapons/v_musket.vtf" )
resource.AddFile( "materials/models/weapons/v_musket_normal.vtf" )
resource.AddFile( "materials/models/weapons/v_musket_RTNL.vtf" )

resource.AddFile( "models/weapons/w_musket/w_musket.dx80.vtx" )
resource.AddFile( "models/weapons/w_musket/w_musket.dx90.vtx" )
resource.AddFile( "models/weapons/w_musket/w_musket.mdl" )
resource.AddFile( "models/weapons/w_musket/w_musket.phy" )
resource.AddFile( "models/weapons/w_musket/w_musket.sw.vtx" )
resource.AddFile( "models/weapons/w_musket/w_musket.vvd" )
resource.AddFile( "models/weapons/musket.dx80.vtx" )
resource.AddFile( "models/weapons/musket.dx90.vtx" )
resource.AddFile( "models/weapons/musket.mdl" )
resource.AddFile( "models/weapons/musket.sw.vtx" )
resource.AddFile( "models/weapons/musket.vvd" )
resource.AddFile( "models/weapons/musket.xbox.vtx" )

--Keg
resource.AddFile( "materials/models/weapons/keg.vmt" )
resource.AddFile( "materials/models/weapons/keg.vtf" )
resource.AddFile( "materials/models/weapons/w_keg.vmt" )
resource.AddFile( "materials/models/weapons/w_keg.vtf" )
resource.AddFile( "materials/models/weapons/hands.vmt" )
resource.AddFile( "materials/models/weapons/hands.vtf" )
resource.AddFile( "materials/models/weapons/hands_normal.vtf" )

resource.AddFile( "models/weapons/w_keg/w_keg.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib01.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib01.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib01.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib01.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib01.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib01.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib02.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib02.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib02.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib02.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib02.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib02.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib03.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib03.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib03.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib03.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib03.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib03.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib04.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib04.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib04.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib04.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib04.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib04.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib05.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib05.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib05.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib05.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib05.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib05.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib06.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib06.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib06.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib06.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib06.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib06.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib07.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib07.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib07.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib07.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib07.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib07.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib08.dx80.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib08.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib08.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib08.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib08.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib08.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib09.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib09.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib09.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib09.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib09.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib09.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib10.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib10.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib10.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib10.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib10.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib10.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib11.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib11.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib11.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib11.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib11.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib11.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib12.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib12.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib12.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib12.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib12.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib12.vvd" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib13.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib13.dx90.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib13.mdl" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib13.phy" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib13.sw.vtx" )
resource.AddFile( "models/weapons/w_keg/w_keg_gib13.vvd" )
resource.AddFile( "models/weapons/keg.dx80.vtx" )
resource.AddFile( "models/weapons/keg.dx90.vtx" )
resource.AddFile( "models/weapons/keg.mdl" )
resource.AddFile( "models/weapons/keg.sw.vtx" )
resource.AddFile( "models/weapons/keg.vvd" )
resource.AddFile( "models/weapons/keg.xbox.vtx")

--Cutlass
resource.AddFile( "models/weapons/w_cutlass2/w_cutlass2.dx80.vtx" )
resource.AddFile( "models/weapons/w_cutlass2/w_cutlass2.dx90.vtx" )
resource.AddFile( "models/weapons/w_cutlass2/w_cutlass2.mdl" )
resource.AddFile( "models/weapons/w_cutlass2/w_cutlass2.phy" )
resource.AddFile( "models/weapons/w_cutlass2/w_cutlass2.sw.vtx" )
resource.AddFile( "models/weapons/w_cutlass2/w_cutlass2.vvd" )
resource.AddFile( "models/weapons/cutlass2.dx80.vtx" )
resource.AddFile( "models/weapons/cutlass2.dx90.vtx" )
resource.AddFile( "models/weapons/cutlass2.mdl" )
resource.AddFile( "models/weapons/cutlass2.sw.vtx" )
resource.AddFile( "models/weapons/cutlass2.vvd" )
resource.AddFile( "models/weapons/cutlass2.xbox.vtx")

resource.AddFile( "materials/models/weapons/cutlass2specmap.vtf" )
resource.AddFile( "materials/models/weapons/w_cutlass2specmap.vtf" )
resource.AddFile( "materials/models/weapons/w_xeal_cutlass2_512.vmt" )
resource.AddFile( "materials/models/weapons/w_xeal_cutlass2_512.vtf" )
resource.AddFile( "materials/models/weapons/xeal_cutlass2_512.vmt" )
resource.AddFile( "materials/models/weapons/xeal_cutlass2_512.vtf" )
resource.AddFile( "materials/models/weapons/xeal_cutlass2_512_normals.vtf" )
resource.AddFile( "materials/models/weapons/xeal_cutlass2_512-blood.vtf" )

--Sounds
resource.AddFile( "sound/psw/explodebarrel.wav" )
resource.AddFile( "sound/psw/impact1.wav" )
resource.AddFile( "sound/weapons/cockpistol-1.wav" )
resource.AddFile( "sound/weapons/cutlass_draw.wav" )
resource.AddFile( "sound/weapons/flcock_draw.wav" )
resource.AddFile( "sound/weapons/flintlock-1.wav" )
resource.AddFile( "sound/weapons/pistolreload.wav" )
resource.AddFile( "sound/weapons/pistolshot.wav" )
resource.AddFile( "sound/weapons/rifle/ssrifle_draw.wav" )
resource.AddFile( "sound/weapons/rifle/ssrifle_fire1.wav" )
resource.AddFile( "sound/weapons/rifle/ssrifle_holster.wav" )
resource.AddFile( "sound/weapons/rifle/ssrifle_reload.wav" )
